name: Test

on: push

jobs:

  build_and_deploy:
    name: Test
    runs-on: ubuntu-20.04

    steps:

      - name: Test
        uses: volta-cli/action@v1
        with:
          node-version: '14'
          npm-version: '7'
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          npm test
